### ISSUE TITLE
Model Parameters not found in config!

### ISSUE THREAD

**Issue by tuanho27** [Hxyou/MSCLIP#1]
Hi there, 

Thanks for your great work!
Just come to test your pretrained model but I see some parameters in Attention_CUST class are not found in config file (default + yml), could you confirm this?, I think it lacks a custom configuration in your repo.
![image](https://user-images.githubusercontent.com/22056468/183612342-169ced19-a9a4-4dd4-a63b-d5f7f8029517.png)
![image](https://user-images.githubusercontent.com/22056468/183612388-b3735087-4f7d-4461-bd81-e4cf52b3c97f.png)

Regards,
TuanHL

**Comment by Hxyou** [comment]
Hi TuanHL, in our config, we didn't specify lora_attn_dim, so it should be 0 according to this [line of code](https://github.com/Hxyou/MSCLIP/blob/42552af6f3fdf719ca89754c81762016ee611091/lib/models/clip_openai_pe_res_v1.py#L346). Then, the code shouldn't jump into line 669 shown in your screenshot, because the [if in this line](https://github.com/Hxyou/MSCLIP/blob/42552af6f3fdf719ca89754c81762016ee611091/lib/models/clip_openai_pe_res_v1.py#L665) isn't true. Can you tell me more about how you triggered this error? Thanks

**Comment by tuanho27** [comment]
Hi,

Thank you for your reply. I see. I've tried to load the pretrained model and run with dummy data successfully. 
The error occurs when I use torch.jit.script(model), which seems to try to compile all custom functions even if it's redundant.
So I think the code is good.

Thanks and BRs,
Tuan HL
